### ISSUE TITLE
add method for getting the attributes for genes

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDbR#6]
or other things in the ID mapping database.

**Comment by Chris-Evelo** [comment]
Didn't we already have that? We at least always considered some things more annotations then "real mappings". On the other hand we had discussions to keep the attributes sparse since with the database ID you can get the attributes from the database itself, which typically gives you the most up-to-date version.

**Comment by egonw** [comment]
We have it in the API, but I did not immediately spot a wrapper method in the R package...

**Comment by Chris-Evelo** [comment]
Understood, missed that

**Comment by egonw** [comment]
Implemented in https://github.com/bridgedb/BridgeDbR/commit/ab6d6146173a3b2d0d440026257b7e1ec55f8f61
